Traceback (most recent call last):
  File "/home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/larsm/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
urn = "URN:NBN:no-nb_digibok_2021011848587"
bok = Counts([urn])

# Fra frekvenslista kan vi se at:
    # "i" har hÃ¸yere frekvens enn "," - da kan vi anta at det er en sakprosatekst
    # "vann" er det sjette mest frekvente ordet, altsÃ¥ handler teksten om vann
    # 348 punktum, dette er en kort tekst. (Punktum ligger rundt 5% av teksters lengde)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[2], line 2[0m
[1;32m      1[0m urn [38;5;241m=[39m [38;5;124m"[39m[38;5;124mURN:NBN:no-nb_digibok_2021011848587[39m[38;5;124m"[39m
[0;32m----> 2[0m bok [38;5;241m=[39m [43mCounts[49m[43m([49m[43m[[49m[43murn[49m[43m][49m[43m)[49m
[1;32m      4[0m [38;5;66;03m# Fra frekvenslista kan vi se at:[39;00m
[1;32m      5[0m     [38;5;66;03m# "i" har hÃ¸yere frekvens enn "," - da kan vi anta at det er en sakprosatekst[39;00m
[1;32m      6[0m     [38;5;66;03m# "vann" er det sjette mest frekvente ordet, altsÃ¥ handler teksten om vann[39;00m
[1;32m      7[0m     [38;5;66;03m# 348 punktum, dette er en kort tekst. (Punktum ligger rundt 5% av teksters lengde)[39;00m

File [0;32m~/anaconda3/envs/digital_tekstanalyse3.10/lib/python3.10/site-packages/dhlab/text/conc_coll.py:166[0m, in [0;36mCounts.__init__[0;34m(self, corpus, words)[0m
[1;32m    161[0m     [38;5;28mself[39m[38;5;241m.[39mcounts [38;5;241m=[39m get_document_frequencies(
[1;32m    162[0m         urns[38;5;241m=[39murnlist(corpus), cutoff[38;5;241m=[39m[38;5;241m0[39m, words[38;5;241m=[39mwords
[1;32m    163[0m     )
[1;32m    165[0m     [38;5;66;03m# Include dhlab and title link in object[39;00m
[0;32m--> 166[0m     [38;5;28mself[39m[38;5;241m.[39mtitle_dct [38;5;241m=[39m {k : v [38;5;28;01mfor[39;00m k, v [38;5;129;01min[39;00m [38;5;28mzip[39m([43mcorpus[49m[38;5;241;43m.[39;49m[43mframe[49m[38;5;241m.[39mdhlabid, corpus[38;5;241m.[39mframe[38;5;241m.[39mtitle)} 
[1;32m    168[0m [38;5;28msuper[39m()[38;5;241m.[39m[38;5;21m__init__[39m([38;5;28mself[39m[38;5;241m.[39mcounts)

[0;31mAttributeError[0m: 'list' object has no attribute 'frame'
AttributeError: 'list' object has no attribute 'frame'

